<?php

namespace App\Filament\Resources\StansResource\Pages;

use App\Filament\Resources\StansResource;
use Filament\Classes\RedirectOnIndexHandler\TraitRedirectOnIndex;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditStans extends EditRecord
{
    use TraitRedirectOnIndex;
    protected static string $resource = StansResource::class;

    protected function getActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        $record->stans?->update([
            'number' => $data['number_temporary_var'],
            'date_start' => $data['date_start_temporary_var'],
            'date_end' => $data['date_end_temporary_var'],
        ]);
        unset($data['number_temporary_var']);
        unset($data['date_start_temporary_var']);
        unset($data['date_end_temporary_var']);

        return parent::handleRecordUpdate($record, $data);
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['number_temporary_var'] = $this->getRecord()->stans->number;
        $data['date_start_temporary_var'] = $this->getRecord()->stans->date_start;
        $data['date_end_temporary_var'] = $this->getRecord()->stans->date_end;

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
